### ISSUE TITLE
Serde closes Streams when writing/reading binary

### ISSUE THREAD

**Issue by NicoVIII** [usix79/Avro.FSharp#1]
The used BinaryWriter and BinaryReader in Serde.fs close the provided stream by default on dispose.
This is a bit unintentional in my opinion because I think the creator of the stream should be in control of the closing as well. And if I want to use the same Stream to write and then read from this is not possible right now (I guess that is why the MemoryStream in the tests had to be recreated after writing).

Would it be possible to give the Writer and Reader the "leaveOpen"-Options to avoid closing the stream? Or could that be an option or config or something so that I could customize this behavior?

**Comment by usix79** [comment]
Hi, thank you for the detailed explanation. I've fixed the bug as you proposed. 
Also I addedlast missing feature into the library - zig-zag encoding for integers. 
Now it is fully compatible with Avro specification and releases as v1.0.
