### ISSUE TITLE
nuget package depends on Avro.FSharp.Annotations, which doesn't exist

### ISSUE THREAD

**Issue by NicoVIII** [usix79/Avro.FSharp#2]
In the new version 1.0 the lib depends on two additional packages, one of them is
Avro.FSharp.Annotations

But this one isn't in nuget, therefore it is not possible for me to install that version.
https://www.nuget.org/packages/Avro.FSharp/#dependencies-body-tab

**Comment by usix79** [comment]
fixed. see version 1.0.1

**Comment by NicoVIII** [comment]
Thank you!
